// <auto-generated />
using System;
using Assignment_2_3_CarlRizk.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Assignment_2_3_CarlRizk.Migrations
{
    [DbContext(typeof(PoliciesDbContext))]
    [Migration("20200221055145_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Assignment_2_3_CarlRizk.Entities.Beneficiary", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int?>("PolicyId")
                        .HasColumnType("int");

                    b.Property<int>("Relationship")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId");

                    b.ToTable("Beneficiaries");
                });

            modelBuilder.Entity("Assignment_2_3_CarlRizk.Entities.Claim", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float?>("ClaimedAmount")
                        .IsRequired()
                        .HasColumnType("real");

                    b.Property<DateTime?>("IncurredDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int?>("policyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("policyId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("Assignment_2_3_CarlRizk.Entities.Policy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("EffectiveDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiryDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("LTRIM(STR(YEAR([EffectiveDate]))) + '-Medical-' + LTRIM(STR([Id]))");

                    b.HasKey("Id");

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("Assignment_2_3_CarlRizk.Entities.Beneficiary", b =>
                {
                    b.HasOne("Assignment_2_3_CarlRizk.Entities.Policy", "Policy")
                        .WithMany("Beneficiaries")
                        .HasForeignKey("PolicyId");
                });

            modelBuilder.Entity("Assignment_2_3_CarlRizk.Entities.Claim", b =>
                {
                    b.HasOne("Assignment_2_3_CarlRizk.Entities.Policy", "Policy")
                        .WithMany("Claims")
                        .HasForeignKey("policyId");
                });
#pragma warning restore 612, 618
        }
    }
}
